### ISSUE TITLE
Connection to database

### ISSUE THREAD

**Issue by Squid1917** [D-Cysteine/nesql-server#1]
How can i use the HyperSQL Database Manager program to conect to the database because I cant find a .db file only the .script file? I also get this error when trying to connect: "java.sql.SQLTransientConnectionException: connection exception: connection failure: org.hsqldb.HsqlException: java.io.EOFException"

**Comment by D-Cysteine** [comment]
HSQLDB has a bit of an odd format; the `.script` file and the `.properties` file together constitute the DB. Are you trying to use the HSQLDB client to open the DB? If so, I think you want something like this for the URL:
```
jdbc:hsqldb:file:containing/directory/path/nesql-db
```

That error that you got would indicate that the DB file might be truncated or corrupt. My (rather old) script file is ~450MB, and the last lines are `INSERT INTO TASK_ITEM_GROUP`; you could do a quick check that yours is a similar size, and has similar ending lines. You can also download a somewhat outdated export from here, if you want something that is known to be good to try with: https://github.com/D-Cysteine/nesql-exporter/releases/tag/GTNH-2.2.9-db

**Comment by Squid1917** [comment]
When will all the other recipes be added. e.g. NASA Workbench and such

**Comment by D-Cysteine** [comment]
I've been planning to export the other recipe types as well, but there are quite a lot of them, so I probably won't get to it for a while
